config/routes.rb
Rails.application.routes.draw do
  # RECIPES
  resources :recipes do
    # NESTED SORTABLE INSTRUCTIONS
    resources :instructions do
      resource :instruction_position, only: :update
    end
    
    # NESTED SORTABLE INGREDIENTS
    resources :ingredients do  
      resource :ingredient_position, only: :update
    end

    # FORM WIZARD
    resources :steps, only: [:show, :update], controller: 'steps_controllers/recipe_steps'

    # LIKEABLE
    post 'likes', to: "likes#create"
    delete 'likes', to: "likes#destroy"
  end
  

  # USERS
  devise_for :users
  resources :users, only: [:index, :show] do
    member do
      get 'user_recipes'
    end
  end
  
  # CONTACTS
  resources :contacts, only: [:new, :create]

  # LAYOUTS
  root to: 'recipes#index'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	
  # == Constants ============================================================
	
  # == Attributes ===========================================================
	
  # == Extensions ===========================================================
	
  # == Relationships ========================================================
  has_many :ingredients, -> { order(position: :asc) }, dependent: :destroy, inverse_of: :recipe
  has_many :instructions, -> { order(position: :asc) }, dependent: :destroy, inverse_of: :recipe
  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: :true
  accepts_nested_attributes_for :instructions, reject_if: :all_blank, allow_destroy: :true
  belongs_to :user
  has_one_attached :photo
  has_many :likes

  include PgSearch::Model
  multisearchable against: [ :name, :description ]

  # == Validations ==========================================================
  with_options if: -> { required_for_step?(:recipe) } do
    validates :name, presence: true, length: { minimum: 2, maximum: 100}
    validates :description, presence: true, length: { minimum: 2, maximum: 750}
    validates :serves, presence: true, numericality: { only_integer: true, in: 1..50 }
  end

  with_options if: -> { required_for_step?(:ingredients) } do
  end

  with_options if: -> { required_for_step?(:instructions) } do
  end

  # == Scopes ===============================================================
  default_scope { where wizard_complete: true }
  scope :wizard_not_completed_only, -> { unscope(where: :wizard_complete).where(wizard_complete: false) }

  # == Callbacks ============================================================
	
  # == Class Methods ========================================================
  enum form_steps: {
    recipe: [:name, :description, :serves, :photo],
    ingredients: [ingredients_attributes: [:id, :description, :_destroy]],
    instructions: [instructions_attributes: [:id, :description, :_destroy]]
  }
  attr_accessor :form_step

  def self.search(query)
    return all unless query.present?

    results = PgSearch.multisearch(query)

    recipes = []
    results.each do |result|
      if result.searchable_type == "Recipe"
        recipes << result.searchable
      elsif result.searchable_type == "User"
        result.searchable.recipes.each do | user_recipe |
          recipes << user_recipe
        end
      else
        recipes << Recipe.find(result.searchable.recipe_id)
      end
    end

    Recipe.where(id: recipes.map(&:id))
  end
	
  # == Instance Methods =====================================================
  def required_for_step?(step)
    # All fields are required if no form step is present
    return true if form_step.nil?
	
    # All fields from previous steps are required
    ordered_keys = self.class.form_steps.keys.map(&:to_sym)
    !!(ordered_keys.index(step) <= ordered_keys.index(form_step))
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]
  before_action :set_recipe, only: %i[ show edit update destroy ]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.search(params[:query])
      .order(created_at: :desc)
      .page(params[:page])
      .without_count
      .per(8)

      skip_policy_scope
  end

  # GET /recipes/1 or /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new wizard_complete: false
    @recipe.ingredients.new
    @recipe.instructions.new
    @recipe.user = current_user
    authorize @recipe
    @recipe.save! validate: false
    redirect_to recipe_step_path(@recipe, Recipe.form_steps.keys.first)
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    authorize @recipe
    @recipe.user = current_user
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: "Recipe was successfully created." }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: "Recipe was successfully updated." }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: "Recipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
      authorize @recipe
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:name, :description, :photo, :serves, ingredients_attributes: [:id, :description, :position, :_destroy], instructions_attributes: [:id, :description, :position, :_destroy])
    end
end

app/views/recipes/_form.html.erb
<div class="main-card">
  <%# DELETE ICON TOP%>
  <%= link_to recipe_path(@recipe), data: { confirm: "Are you sure you want to delete the recipe #{@recipe.name}?" }, method: :delete do %>
    <i class="top-icon fas fa-trash-alt"></i>
  <% end %>

  <%= simple_form_for(@recipe) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div id="edit-recipe" class="edit-form">
      <%= render "recipe_form", f: f %>
      <br>
      <div class="save-recipe">
        <%= f.button :submit, "✓ Save recipe", class: "btn-ghost btn-green" %>
      </div>  
    </div>
    
    <div id="edit-ingredients" class="edit-form">
      <%= render "ingredients_form", f: f %>
      <br>
      <div class="save-recipe">
        <%= f.button :submit, "✓ Save recipe", class: "btn-ghost btn-green" %>
      </div>
    </div>

    <div id="edit-instructions" class="edit-form">
      <%= render "instructions_form", f: f %>
      <br>
      <div class="save-recipe">
        <%= f.button :submit, "✓ Save recipe", class: "btn-ghost btn-green" %>
      </div>
    </div>

  <% end %>

  <%# DELETE ICON BOTTOM%>
  <%= link_to recipe_path(@recipe), data: { confirm: "Are you sure you want to delete the recipe #{@recipe.name}?" }, method: :delete do %>
    <i class="bottom-icon fas fa-trash-alt"></i>
  <% end %>
</div>
 

app/views/recipes/_ingredient_fields.html.erb
<%= content_tag :div, class: "nested-fields", data: { new_record: form.object.new_record?, id: form.object.id } do %>
  <%= form.hidden_field :id %>
  <div data-nested-form-target="inputElement" class="form-inputs inline-form ingredient-show">
    <div class="handle">
      <i class="fas fa-grip-lines"></i>
    </div>

    <%= form.input  :description, 
                    label: "Description", 
                    class: "form-input",
                    as: :text, 
                    placeholder: "e.g. 250g of flour",
                    input_html: { data: { controller: "textarea-autogrow" } } 
                    %>
    <%= link_to "#", data: { action: "click->nested-form#remove_association" } do %>
      <i class="inline-delete fas fa-trash-alt"></i>
    <% end %>
  </div>
  <%= form.hidden_field :_destroy %>
<% end %>

app/views/recipes/_ingredients_form.html.erb
<h4>Ingredients</h4>
<br>
<div data-controller="nested-form drag" data-drag-url="/recipes/<%= @recipe.id %>/ingredients/:id/ingredient_position">
  <template data-nested-form-target="template">
    <%= f.fields_for :ingredients, Ingredient.new, child_index: 'NEW_RECORD' do |ingredient| %>
      <%= render "recipes/ingredient_fields", form: ingredient %>
    <% end %>
  </template>   

  <%= f.fields_for :ingredients, @recipe.ingredients.order(position: :asc), include_id: false do |ingredient|%>
    <%= render "recipes/ingredient_fields", form: ingredient %>
  <% end %>
  
  <div class="add-association" data-nested-form-target="links">
    <%= link_to "+ Add ingredient", "#", class: "btn-ghost", data: { action: "click->nested-form#add_association" } %>
  </div>
</div>

app/views/recipes/_instruction_fields.html.erb
<%= content_tag :div, class: "nested-fields", data: { new_record: form.object.new_record?, id: form.object.id } do %>
  <%= form.hidden_field :id %>
  <div data-nested-form-target="inputElement" class="form-inputs inline-form ingredient-show">
    <div class="handle">
      <i class="fas fa-grip-lines"></i>
    </div>

    <div class="counter"><h4></h4></div>
    <%= form.input  :description,
                    label: "Description", 
                    class: "form-input",
                    placeholder: "Describe what to do for this step",
                    input_html: { data: { controller: "textarea-autogrow" } } 
                    %>
    
    <%= link_to "#", data: { action: "click->nested-form#remove_association" } do %>
      <i class="inline-delete fas fa-trash-alt"></i>
    <% end %>
  </div>
  <%= form.hidden_field :_destroy %>
<% end %>

app/views/recipes/_instructions_form.html.erb
<h4>Instructions</h4>
<br>
<div data-controller="nested-form drag" data-drag-url="/recipes/<%= @recipe.id %>/instructions/:id/instruction_position"> 
  <template data-nested-form-target="template">
    <%= f.fields_for :instructions, Instruction.new, child_index: 'NEW_RECORD' do |instruction| %>
      <%= render "/recipes/instruction_fields", form: instruction %>
    <% end %>
  </template>   

  <%= f.fields_for :instructions, @recipe.instructions.order(position: :asc), include_id: false do |instruction|%>
    <%= render "/recipes/instruction_fields", form: instruction %>
  <% end %>

  <div class="add-association" data-nested-form-target="links">
    <%= link_to "+ Add instruction", "#", class: "btn-ghost", data: { action: "click->nested-form#add_association" } %>
  </div>
</div>

app/views/recipes/_recipe_cards.html.erb
<div class="card-recipe">
  
  <%= link_to recipe_path(recipe) do %>
    <% if recipe.photo.attached? %>
      <%= cl_image_tag recipe.photo.key, :transformation=>[
      {:width=>800, :height=>800}], 
      class: "card-image" %>
    <% else %>
      <%= image_tag "sample_meal.jpg", class: "card-image" %>
    <% end %>
  <% end %>

  <div class="card-recipe-infos">
    <%= link_to recipe_path(recipe) do %>
      <div>
        <h2><%= highlight(recipe.name, query_array) %></h2>
        <p><%= highlight(recipe.description, query_array) %></p>
      </div>
    <% end %>

    <%= link_to user_path(recipe.user) do %>
      <% if recipe.user.avatar.attached? %> 
        <%= cl_image_tag recipe.user.avatar.key, :transformation=>[
          {:width=>200, :height=>200, :gravity=>"face", :radius=>"max", :crop=>"thumb"}], 
          class: "card-recipe-user avatar", 'aria-haspopup': true, 'aria-expanded': false %>
      <% else %>
        <%= image_tag "default_avatar_square.png", class: "card-recipe-user avatar", alt: "avatar", 'aria-haspopup': true, 'aria-expanded': false %>
      <% end %>
    <% end %>

  </div>

  <div data-controller="like" class="card-recipe-like" data-like-url="/recipes/<%= recipe.id %>/likes">
    <i data-action="click->like#save" data-like-target="heart" class="<%= liked?(recipe) %> fa-heart"></i>
  </div>

</div>

app/views/recipes/_recipe_form.html.erb
<h4>Recipe description</h4>
<br>
<div class="form-inputs">
  <%= f.input :name,
              required: true %>
  <%= f.input :description,
              required: true,
              input_html: { data: { controller: "textarea-autogrow" } } %>
  <div class="inline-form label-inline">
    <div>
      <p>Serves how many? *</p>
    </div>
    <%= f.input :serves, 
                label: false,
                required: true, 
                as: :integer %>
  </div>
  <br>
  <div class="image-upload" data-controller="photo-preview">
    <%= f.input :photo, 
                input_html: { class: 'd-none', data: { action: "click->photo-preview#photo_input", photo_preview_target: "photoInput" } }, 
                label_html: { class: 'btn-ghost' }, 
                label: '📷 Upload a photo',
                hint: "You can also do this later" %>
    <%= image_tag "", width: 300, class: "hidden", id: "photo-preview", data: { photo_preview_target: "photoPreview" } %>
  </div>
</div>

app/views/recipes/edit.html.erb
<h4>Edit recipe</h4>
<br>
<%# BUTTONS TOP %>
<%= link_to @recipe do %>
  <i class="fas fa-arrow-left btn-ghost"></i>
<% end %>
<%= link_to 'All recipes', recipes_path, class: "btn-ghost" %>

<%= render 'form', recipe: @recipe %>
<br>

<%# BUTTONS BOTTOM %>
<%= link_to @recipe do %>
  <i class="fas fa-arrow-left btn-ghost"></i>
<% end %>
<%= link_to 'All recipes', recipes_path, class: "btn-ghost" %>

app/views/recipes/index.html.erb
<%= link_to '+ New recipe', new_recipe_path, class: "btn btn-ghost btn-coral" %>
<br><br>

<%# Search bar %>
<%= simple_form_for :search, url: recipes_path, method: :get do |f| %>
  <div class="search-form-control form-group">
    <%= text_field_tag :query,
      params[:query],
      class: "form-control string required",
      type: "text",
      id: "search_query" 
      %>
    <button name="button" type="submit" class="btn btn-ghost">
      <i class="fas fa-search"></i> Search
    </button>
  </div>
<% end %>

<%# Result counter %>
<% if params[:query].blank? %>
  <p><%= pluralize Recipe.all.count, 'recipe' %> available</p>
<% else %>
  <p><%= pluralize @recipes.count, 'result' %> for <code><%= params[:query] %></code></p>
<% end %>

<%# Recipes %>
<div class="index-grid">
  <% @recipes.each do |recipe| %>
    <%= render "recipes/recipe_cards", recipe: recipe %>
  <% end %>
</div>
<br>

<%= link_to_prev_page @recipes, 'Previous Page', class: 'btn-ghost' %>
<%= link_to_next_page @recipes, 'Next Page', class: 'btn-ghost' %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<%# METADATA %>
<% content_for :meta_title, "#{@recipe.name} - #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @recipe.description %>
<% if @recipe.photo.attached? %>
  <% content_for :meta_image, cl_image_path(@recipe.photo.key) %>
<% else %>
  <% content_for :meta_image, cl_image_path("sample_meal.jpg") %>
<% end %>
<%# /METADATA %>
  
  <%# ACTION BUTTON TOP %>
  <div class="action-btns">
    <%= link_to 'Back to recipes', recipes_path, class: "recipes-btn btn-ghost" %>
    <% if policy(@recipe).update? %>
      <%= link_to edit_recipe_path(@recipe) do %>
        <i class="show-icon fas fa-edit"></i>
      <% end %>
    <% end %>

    <% if policy(@recipe).destroy? %>
      <%= link_to recipe_path(@recipe), data: { confirm: "Are you sure you want to delete recipe #{@recipe.name}?" }, method: :delete do %>
        <i class="show-icon fas fa-trash-alt"></i>
      <% end %>
    <% end %>
  </div>

<div class="main-card recipe">
  
  <%# PHOTO %>
  <div class="photo-show">
    <% if @recipe.photo.attached? %>
      <%= cl_image_tag @recipe.photo.key, :transformation=>[
        {:width=>800, :height=>800}], 
        class: "card-image" %>
    <% else %>
      <%= image_tag "sample_meal.jpg", class: "card-image", :width=>200 %>
    <% end %>
  </div>

  <%# DESCRIPTION %>
  <div class="description-show">
    <h4><%= @recipe.name %></h4>
    <p><%= @recipe.description %></p>
    
    <%# USER AVATAR %>
    <div class="user-show">
      <%= link_to user_path(@recipe.user) do %>
        <% if @recipe.user.avatar.attached? %> 
          <%= cl_image_tag @recipe.user.avatar.key, :transformation=>[
            {:width=>200, :height=>200, :gravity=>"face", :radius=>"max", :crop=>"thumb"}], 
            class: "card-recipe-user avatar", 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
          <%= image_tag "default_avatar_square.png", class: "card-recipe-user avatar", alt: "avatar", 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
      <% end %>

      <%# USER NAME %>
      <div class="user-name">
        <%= link_to user_path(@recipe.user) do %>
          <small><p><%= @recipe.user.full_name %></p></small>
        <% end %>
      </div>
    </div>

    <%# LIKE BUTTON %>
    <div data-controller="like" class="card-recipe-like" data-like-url="/recipes/<%= @recipe.id %>/likes">
      <i data-action="click->like#save" data-like-target="heart" class="<%= liked?(@recipe) %> fa-heart"></i>
    </div>
    
    <%# EDIT BUTTON %>
    <% if policy(@recipe).update? %>
      <br>
      <%= link_to 'Edit description', edit_recipe_path(@recipe, anchor: "edit-recipe"), class: "btn btn-ghost btn-coral" %>
      <%# OLD LINK TO WIZARD %>
      <%#= link_to 'Edit description', recipe_step_path(@recipe, :recipe), class: "btn btn-ghost btn-coral" %>
    <% end %>
  </div>
</div>

<%# INGREDIENTS %>
<div class="main-card">
  <h4>Ingredients</h4>
  <p>Ingredients serve <strong><%= @recipe.serves %></strong> <%= @recipe.serves == 1 ? "person" : "persons" %></p>
  <% @recipe.ingredients.each do |ingredient| %>
    <div class="ingredient-show">
      <p><%= ingredient.description %></p>
    </div>
  <% end %>
  <% if policy(@recipe).update? %>
    <br>
    <%= link_to 'Edit ingredients', edit_recipe_path(@recipe, anchor: "edit-ingredients"), class: "btn btn-ghost btn-coral" %>
  <% end %>
</div>

<%# INSTRUCITONS %>
<div data-controller="nested-form" class="main-card">
  <h4>Instructions</h4>
  <% @recipe.instructions.each do |instruction| %>
    <div data-nested-form-target="inputElement" class="ingredient-show">
      <div class="counter"><h4></h4></div>
      <div class="instruction-description"><p>
        <%= instruction.description %>
      </p>
      </div>
    </div>
  <% end %>
  <% if policy(@recipe).update? %>
    <br>
    <%= link_to 'Edit instructions', edit_recipe_path(@recipe, anchor: "edit-instructions"), class: "btn btn-ghost btn-coral" %>
  <% end %>
</div>
<br>
<div class="action-btns">
  <%= link_to 'Back to recipes', recipes_path, class: "recipes-btn btn-ghost" %>
    
  <% if policy(@recipe).update? %>
    <%= link_to edit_recipe_path(@recipe) do %>
      <i class="show-icon fas fa-edit"></i>
    <% end %>
  <% end %>

  <% if policy(@recipe).destroy? %>
    <%= link_to recipe_path(@recipe), data: { confirm: "Are you sure you want to delete recipe #{@recipe.name}?" }, method: :delete do %>
      <i class="show-icon fas fa-trash-alt"></i>
    <% end %>
  <% end %>
</div>