config/routes.rb
Rails.application.routes.draw do
  # RECIPES
  resources :recipes do
    # NESTED SORTABLE INSTRUCTIONS
    resources :instructions do
      resource :instruction_position, only: :update
    end
    
    # NESTED SORTABLE INGREDIENTS
    resources :ingredients do  
      resource :ingredient_position, only: :update
    end

    # FORM WIZARD
    resources :steps, only: [:show, :update], controller: 'steps_controllers/recipe_steps'

    # LIKEABLE
    post 'likes', to: "likes#create"
    delete 'likes', to: "likes#destroy"
  end
  

  # USERS
  devise_for :users
  resources :users, only: [:index, :show] do
    member do
      get 'user_recipes'
    end
  end
  
  # CONTACTS
  resources :contacts, only: [:new, :create]

  # LAYOUTS
  root to: 'recipes#index'
end

app/models/user.rb
class User < ApplicationRecord
# == Constants ============================================================
  
  # == Attributes ===========================================================
  
  # == Extensions ===========================================================
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  
  
  # == Relationships ========================================================
  has_many :recipes
  has_one_attached :avatar
  has_many :likes
  
  include PgSearch::Model
  multisearchable against: [ :first_name, :last_name ]

  # == Validations ==========================================================
  # validates :username, uniqueness: true
  # validates :username, presence: true

  # == Scopes ===============================================================

  # == Callbacks ============================================================
  after_create :send_welcome_email

  # == Class Methods ========================================================
  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  # == Instance Methods =====================================================

  private

  def send_welcome_email
    UserMailer.with(user: self).welcome.deliver_now
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :show ]
  before_action :set_user, only: %i[ show user_recipes edit update destroy ]

  def show
    likes = @user.likes
    li_recipes = [] 
    likes.each do | like |
      li_recipes << like.recipe
    end
    li_recipes
    
    @liked_recipes = Recipe.where(id: li_recipes.map(&:id))
    @user_recipes = @user.recipes

    query_and_respond(@liked_recipes)
  end
  
  def user_recipes
    @user_recipes = @user.recipes
    query_and_respond(@user_recipes)
  end
  
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
    authorize @user
  end
  
  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:email)
  end
  
  # Query for both user_recipes and liked_recipes
  def query_and_respond(recipes)
    if params[:query].present?
      sql_query = "name ILIKE :query OR description ILIKE :query"
      recipes = recipes.where(sql_query, query: "%#{params[:query]}%")
    end
  
    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: 'list.html', locals: { recipes: recipes } }
    end
  end
end

app/views/users/_list.html.erb
<div data-refresh-list-target="list">
  
  <% if params[:query].blank? %>
    <p><%= pluralize recipes.count, 'recipe' %> available</p>
  <% else %>
    <p><%= pluralize recipes.count, 'result' %> for <code><%= params[:query] %></code></p>
  <% end %>
  
  <div class="index-grid">
    <% recipes.each do |recipe| %>
      <%= render "recipes/recipe_cards.html", recipe: recipe %>
    <% end %>
  </div>

</div>

app/views/users/_search_bar.html.erb
<div class="search-form-control form-group">
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: 'Search recipe name or description',
    type: "text",
    data: {
      refresh_list_target: 'searchInput',
      action: "keyup->refresh-list#update"
    } %>
</div>

app/views/users/show.html.erb
<%# METADATA %>
<% content_for :meta_title, "#{@user.first_name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, "Check out their latest recipes." %>
<% if @user.avatar.attached? %>
  <% content_for :meta_image, cl_image_path(@user.avatar.key) %>
<% else %>
  <% content_for :meta_image, cl_image_path("default_avatar_square.png") %>
<% end %>
<%# /METADATA %>

<h4 class="title-profile">
  <% if current_user == @user %>
    Your profile
  <% else %>
    <%= @user.first_name.possessive %> profile
  <% end %>
</h4>
<br>

<div class="pc-tab">
<input checked="checked" id="tab1" type="radio" name="pct" />
<input id="tab2" type="radio" name="pct" />
<input id="tab3" type="radio" name="pct" />
  <nav>
    <ul>
      <%# USER'S RECIPES TAB %>
      <li class="tab1">
        <label for="tab1"><%= current_user == @user ? "Your recipes" : "#{@user.first_name.possessive} recipes"%></label>
      </li>
      
      <%# liked RECIPES TAB %>
      <li class="tab2">
        <label for="tab2">Liked recipes</label>
      </li>
      
      <%# PROFILE TAB %>
      <li class="tab3">
        <label for="tab3">Profile</label>
      </li>
    </ul>
  </nav>
  <section>
  <br>

    <%# USER'S RECIPES TAB %>
    <div class="tab1">
      <div data-controller="refresh-list">
      
        <%# Search bar %>
        <%= simple_form_for :search, url: user_recipes_user_path(@user), method: :get, data: {
        refresh_list_target: 'form' } do |f| %>
          <%= render 'users/search_bar' %>
        <% end %>
        <%# List of results %>
        <% if @user_recipes.any? %>
          <%= render 'users/list', recipes: @user_recipes %>
        <% else %>
          <p>
            <%= current_user == @user ? "You haven't created any recipes yet" : "#{@user.first_name} hasn't created any recipes yet"%>
          </p>
          <br>
          <% if current_user == @user %>
            <%= link_to "+ Go ahead and create one", new_recipe_path, class: "btn-ghost btn-coral" %>
          <% end %>
        <% end %>

      </div>
    </div>

    <%# LIKED RECIPES TAB %>
    <div class="tab2">
      <div data-controller="refresh-list">

        <%# Search bar %>
        <%= simple_form_for :search, url: user_path(@user), method: :get, data: {
        refresh_list_target: 'form' } do |f| %>
          <%= render 'users/search_bar' %>
        <% end %>
        
        <%# List of results %>
        <% if @liked_recipes.any? %>
          <%= render 'users/list', recipes: @liked_recipes %>           
        <% else %>
          <p>
            <%= current_user == @user ? "You have no liked recipes yet. Just click on the heart on any recipe and it will magically show up here." : "#{@user.first_name} has no liked recipes yet"%>
          </p>
        <% end %>

      </div>
    </div>

    <%# PROFILE TAB %>
    <div class="tab3">
      <div class="main-card">
      <%# AVATAR %>
      <% if @user.avatar.attached? %>
        <%= cl_image_tag @user.avatar.key, :transformation=>[
          {:width=>300, :height=>300, :gravity=>"face", :radius=>"max", :crop=>"thumb"}], 
          class: "avatar avatar-very-large" %>
      <% else %>
        <%= image_tag "default_avatar_square.png", class: "avatar avatar-very-large" %>
      <% end %>
      <br><br>

      <%# PROFILE DETAILS %>
      <p><strong>Name:</strong> <%= @user.full_name %></p>

      <%# PUNDIT UPDATE %>
      <% if policy(@user).update? %>
        <p><strong>Email:</strong> <%= @user.email %>*</p>
        <small><p>* This is only visible to you.</p></small>
        <%= link_to "Edit profile", edit_user_registration_path, class: "btn btn-ghost" %>
      <% end %>
      </div>
    </div>
  </section>
</div>