config/routes.rb
Rails.application.routes.draw do
  # RECIPES
  resources :recipes do
    # NESTED SORTABLE INSTRUCTIONS
    resources :instructions do
      resource :instruction_position, only: :update
    end
    
    # NESTED SORTABLE INGREDIENTS
    resources :ingredients do  
      resource :ingredient_position, only: :update
    end

    # FORM WIZARD
    resources :steps, only: [:show, :update], controller: 'steps_controllers/recipe_steps'

    # LIKEABLE
    post 'likes', to: "likes#create"
    delete 'likes', to: "likes#destroy"
  end
  

  # USERS
  devise_for :users
  resources :users, only: [:index, :show] do
    member do
      get 'user_recipes'
    end
  end
  
  # CONTACTS
  resources :contacts, only: [:new, :create]

  # LAYOUTS
  root to: 'recipes#index'
end

app/views/shared/_analytics.erb
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MCMNLVP"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

app/views/shared/_contact.html.erb
<br>
<br>
<div class="contact-btn">
  <%= link_to "✉️ Contact", new_contact_path, class: "btn-ghost" %>
</div>

app/views/shared/_facebook_open_graph_data.html.erb
<meta property="og:title" content="<%= meta_title %>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<%= request.original_url %>" />
<meta property="og:image" content="<%= meta_image %>" />
<meta property="og:description" content="<%= meta_description %>" />
<meta property="og:site_name" content="<%= meta_title %>" />

app/views/shared/_flashes.html.erb
<%# if notice %>
  <%# <div class="alert alert-info alert-dismissible fade show m-1" role="alert"> %>
    <%#= notice %>
    <%# <button type="button" class="close" data-dismiss="alert" aria-label="Close"> %>
      <%# <span aria-hidden="true">&times;</span> %>
    <%# </button> %>
  <%# </div> %>
<%# end %>
<%# if alert %>
  <%# <div class="alert alert-warning alert-dismissible fade show m-1" role="alert"> %>
    <%#= alert %>
    <%# <button type="button" class="close" data-dismiss="alert" aria-label="Close"> %>
      <%# <span aria-hidden="true">&times;</span> %>
    <%# </button> %>
  <%# </div> %>
<%# end %>

<% if notice %>
  <div class="flash flash-success alert alert-dismissible fade show" role="alert">
    <span style="margin-right: 6px"><strong>Yay!</strong> 🎉
    <%= notice %>
    </span>
    <a data-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

<%# if error %>
  <%# <div class="flash flash-warning alert alert-dismissible fade show" role="alert"> %>
    <%# <span style="margin-right: 6px"><strong>Mmh</strong> 🤔  %>
    <%#= notice %>
    <%# </span> %>
    <%# <a data-dismiss="alert" aria-label="Close"> %>
      <%# <i class="fas fa-times"></i> %>
    <%# </a> %>
  <%# </div> %>
<%# end %>

<% if alert %>
  <div class="flash flash-danger alert alert-dismissible fade show" role="alert">
    <span style="margin-right: 6px"><strong>Oops!</strong> 😱
    <%= alert %>
    </span>
    <a data-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    <i class="fas fa-heart"></i> Margareti
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo_1.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Contact", new_contact_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.avatar.attached? %>
            <%= cl_image_tag current_user.avatar.key, :transformation=>[
              {:width=>200, :height=>200, :gravity=>"face", :radius=>"max", :crop=>"thumb"},
              {:width=>200, :crop=>"scale"}], 
              class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "default_avatar_square.png", class: "avatar dropdown-toggle", id: "navbarDropdown", alt: "avatar", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Get in touch", new_contact_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <li class="nav-item active">
        <%= link_to "Contact", new_contact_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_twitter_card_data.html.erb
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
<meta name="twitter:title" content="<%= meta_title %>">
<meta name="twitter:description" content="<%= meta_description %>">
<meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
<meta name="twitter:image:src" content="<%= meta_image %>">